import { exportHTMLToPDF } from './exportUtils'
import type { SubscriptionPayment } from '../types/subscriptionPayment'

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

export function buildSubscriptionPaymentReceiptHTML(args: {
  payment: SubscriptionPayment
  companyName?: string
}): string {
  const { payment, companyName } = args
  const currency = payment.currency || 'INR'
  const symbol =
    currency === 'INR' ? '₹' : currency === 'USD' ? '$' : currency === 'EUR' ? '€' : currency === 'GBP' ? '£' : ''

  const line = (label: string, value: string) =>
    `<tr><td style="padding:6px 0;color:#6b7280">${escapeHtml(label)}</td><td style="padding:6px 0;text-align:right;font-weight:600;color:#111827">${escapeHtml(value)}</td></tr>`

  const createdAt = new Date(payment.created_at).toLocaleString('en-IN')
  const status = (payment.payment_status || '').toUpperCase()
  const gateway = (payment.payment_gateway || 'N/A').toUpperCase()
  const method = (payment.payment_method || 'N/A').toUpperCase()

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Subscription Payment Receipt</title>
    <style>
      *{box-sizing:border-box}
      body{font-family:Arial, sans-serif; background:#fff; color:#111827; margin:0; padding:24px;}
      .card{max-width:720px; margin:0 auto; border:1px solid #e5e7eb; border-radius:12px; padding:18px;}
      .row{display:flex; justify-content:space-between; gap:12px; flex-wrap:wrap}
      .muted{color:#6b7280}
      .title{font-size:20px; font-weight:800; margin:0}
      .badge{display:inline-block; padding:4px 10px; border-radius:999px; font-size:12px; font-weight:700; border:1px solid #e5e7eb}
      .badge.ok{background:#ecfdf5; border-color:#a7f3d0; color:#065f46}
      .badge.pending{background:#fffbeb; border-color:#fde68a; color:#92400e}
      .badge.fail{background:#fef2f2; border-color:#fecaca; color:#991b1b}
      table{width:100%; border-collapse:collapse; margin-top:12px}
      .hr{height:1px; background:#e5e7eb; margin:14px 0}
      .big{font-size:18px; font-weight:800}
      .foot{margin-top:12px; font-size:12px; color:#6b7280; text-align:center}
      @media print{ body{padding:0} .card{border:none} }
    </style>
  </head>
  <body>
    <div class="card">
      <div class="row" style="align-items:flex-start">
        <div>
          <p class="title">Subscription Payment Receipt</p>
          <p class="muted" style="margin:6px 0 0 0">${escapeHtml(companyName || '')}</p>
        </div>
        <div style="text-align:right">
          <span class="badge ${payment.payment_status === 'success' ? 'ok' : payment.payment_status === 'failed' ? 'fail' : 'pending'}">${escapeHtml(status)}</span>
          <div class="muted" style="margin-top:6px">#{payment.id}</div>
        </div>
      </div>

      <div class="hr"></div>

      <table>
        ${line('Date', createdAt)}
        ${line('Plan', (payment.subscription_tier || '').toUpperCase())}
        ${line('Duration', `${payment.duration_months} month(s)`)}
        ${payment.subscription_start_date ? line('Subscription Start', payment.subscription_start_date) : ''}
        ${payment.subscription_end_date ? line('Subscription End', payment.subscription_end_date) : ''}
        ${line('Gateway', gateway)}
        ${line('Method', method)}
      </table>

      <div class="hr"></div>

      <table>
        ${line('Base Amount', `${symbol}${payment.amount.toFixed(2)}`)}
        ${line('GST', `${symbol}${payment.gst_amount.toFixed(2)}`)}
        ${line('Gateway Fee', `${symbol}${payment.gateway_fee.toFixed(2)}`)}
        <tr>
          <td style="padding:10px 0;font-weight:800">Total</td>
          <td style="padding:10px 0;text-align:right" class="big">${escapeHtml(`${symbol}${payment.total_amount.toFixed(2)}`)}</td>
        </tr>
      </table>

      <div class="hr"></div>

      <table>
        ${payment.gateway_order_id ? line('Order ID', payment.gateway_order_id) : ''}
        ${payment.gateway_payment_id ? line('Payment ID', payment.gateway_payment_id) : ''}
        ${payment.notes ? line('Notes', payment.notes) : ''}
      </table>

      <div class="foot">
        This receipt is generated by HisabKitab-Pro.<br/>
        <strong style="color:#4f46e5;">Powered by HisabKitab Pro · <a href="https://hisabkitabpro.com" target="_blank" rel="noopener">hisabkitabpro.com</a></strong>
      </div>
    </div>
  </body>
</html>`
}

export function openSubscriptionReceiptInNewWindow(args: { payment: SubscriptionPayment; companyName?: string }): void {
  const html = buildSubscriptionPaymentReceiptHTML(args)
  const w = window.open('', '_blank')
  if (!w) {
    alert('Please allow popups to view receipt')
    return
  }
  w.document.open()
  w.document.write(html)
  w.document.close()
}

export async function downloadSubscriptionReceiptPDF(args: {
  payment: SubscriptionPayment
  companyName?: string
}): Promise<void> {
  const html = buildSubscriptionPaymentReceiptHTML(args)
  const id = `subscription-receipt-${args.payment.id}-${Date.now()}`
  const container = document.createElement('div')
  container.id = id
  container.style.position = 'fixed'
  container.style.left = '-99999px'
  container.style.top = '0'
  container.style.width = '800px'
  container.innerHTML = html
  document.body.appendChild(container)
  try {
    await exportHTMLToPDF(id, `Subscription_Receipt_${args.payment.id}`, { format: 'a4', orientation: 'portrait', margin: 10 })
  } finally {
    container.remove()
  }
}

